version: '3.8'

services:
  app:
    build: .
    environment:
      IMPORT_KEY: ${IMPORT_KEY}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
